### ISSUE TITLE
Error on Prompt Entered

### ISSUE THREAD

**Issue by Dmw789** [microsoft/semantic-kernel-starters#94]
**Describe the bug**
I get the following error after setting up and running the app for the first time:

Exception has occurred: CLR/Microsoft.SemanticKernel.Http.HttpOperationException
An exception of type 'Microsoft.SemanticKernel.Http.HttpOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unrecognized request argument supplied: functions
Status: 404 (model_error)

Content:
{
  "error": {
    "message": "Unrecognized request argument supplied: functions",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

Headers:
Access-Control-Allow-Origin: REDACTED
x-ms-region: REDACTED
x-ratelimit-remaining-tokens: REDACTED
apim-request-id: REDACTED
X-Request-ID: REDACTED
ms-azureml-model-error-reason: REDACTED
ms-azureml-model-error-statuscode: REDACTED
x-ms-client-request-id: 55d2f70c-33d7-4c7e-a003-0332edeb6f88
x-ratelimit-remaining-requests: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 08 Dec 2023 22:11:36 GMT
Content-Length: 162
Content-Type: application/json'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Azure.RequestFailedException : Unrecognized request argument supplied: functions
Status: 404 (model_error)

Content:
{
  "error": {
    "message": "Unrecognized request argument supplied: functions",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

Headers:
Access-Control-Allow-Origin: REDACTED
x-ms-region: REDACTED
x-ratelimit-remaining-tokens: REDACTED
apim-request-id: REDACTED
X-Request-ID: REDACTED
ms-azureml-model-error-reason: REDACTED
ms-azureml-model-error-statuscode: REDACTED
x-ms-client-request-id: 55d2f70c-33d7-4c7e-a003-0332edeb6f88
x-ratelimit-remaining-requests: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 08 Dec 2023 22:11:36 GMT
Content-Length: 162
Content-Type: application/json
   at Azure.Core.HttpPipelineExtensions.<ProcessMessageAsync>d__0.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.AI.OpenAI.OpenAIClient.<GetChatCompletionsStreamingAsync>d__16.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.ClientCore.<RunRequestAsync>d__36`1.MoveNext()

**To Reproduce**
Follow along with the readme and run the app, when prompted, I typed
User > Hello

**Desktop (please complete the following information):**
OS: Windows 10.0.19045
IDE: VSCode
NuGet Package Version: 1.0.0-rc3

**Additional context**
Completed test with GPT-35-turbo deployed in Azure OpenAI

The error causes a break to happen at line 49 of Program.cs

**Comment by ksivamuthu** [comment]
Please try with the model that has functions enabled - version 0613. v0613 has function calling support. If you try the model version default v0301, you may not have function calling support - that errors in "Unrecognized request argument supplied: functions"
